import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import HomeButton from "@/components/HomeButton";
import VoiceMicButton from "@/components/VoiceMicButton";
import { useVoiceInput } from "@/hooks/useVoiceInput";

interface PlanReviewViewProps {
  planData?: any;
  onAccept: () => void;
  onHome: () => void;
  onBack: () => void;
}

type ReviewState = "decision" | "feedback" | "processing";

const convertToMarkdown = (data: any): string => {
  if (!data) return "";
  
  let markdown = "# Strategic Plan\n\n";

  // Add objective and goals
  if (data.master_prompt) {
    const mp = data.master_prompt;
    markdown += `## Objective\n\n${mp.objective}\n\n`;
    
    if (mp.goals && mp.goals.length) {
      markdown += `## Goals\n\n`;
      mp.goals.forEach((goal: string) => {
        markdown += `- ${goal}\n`;
      });
      markdown += `\n`;
    }

    if (mp.constraints_and_requirements) {
      markdown += `## Constraints & Requirements\n\n`;
      const cr = mp.constraints_and_requirements;
      if (cr.functional) {
        markdown += `### Functional\n\n`;
        cr.functional.forEach((item: string) => {
          markdown += `- ${item}\n`;
        });
        markdown += `\n`;
      }
      if (cr['non-functional']) {
        markdown += `### Non-Functional\n\n`;
        cr['non-functional'].forEach((item: string) => {
          markdown += `- ${item}\n`;
        });
        markdown += `\n`;
      }
    }

    if (mp.success_criteria) {
      markdown += `## Success Criteria\n\n`;
      const sc = mp.success_criteria;
      if (sc.functional) {
        markdown += `### Functional\n\n`;
        sc.functional.forEach((item: string) => {
          markdown += `- ${item}\n`;
        });
        markdown += `\n`;
      }
      if (sc['non-functional']) {
        markdown += `### Non-Functional\n\n`;
        sc['non-functional'].forEach((item: string) => {
          markdown += `- ${item}\n`;
        });
        markdown += `\n`;
      }
    }

    if (mp.key_deliverables && mp.key_deliverables.length) {
      markdown += `## Key Deliverables\n\n`;
      mp.key_deliverables.forEach((item: string) => {
        markdown += `- ${item}\n`;
      });
      markdown += `\n`;
    }
  }

  // Add strategic roadmap
  if (data.strategic_roadmap) {
    const sr = data.strategic_roadmap;
    markdown += `## Strategic Roadmap\n\n`;
    
    if (sr.vision_statement) {
      markdown += `### Vision\n\n${sr.vision_statement}\n\n`;
    }

    if (sr.key_phases && sr.key_phases.length) {
      markdown += `### Key Phases\n\n`;
      sr.key_phases.forEach((phase: any) => {
        markdown += `#### ${phase.name} (${phase.duration})\n\n`;
        if (phase.activities) {
          phase.activities.forEach((activity: string) => {
            markdown += `- ${activity}\n`;
          });
        }
        markdown += `\n`;
      });
    }

    if (sr.north_star_metrics && sr.north_star_metrics.length) {
      markdown += `### North Star Metrics\n\n`;
      sr.north_star_metrics.forEach((metric: string) => {
        markdown += `- ${metric}\n`;
      });
      markdown += `\n`;
    }
  }

  return markdown;
};

const mockMarkdownSpec = `# Technical Architecture Specification

## 1. System Overview

\`\`\`
PROJECT: concept-generator-v1
TYPE: web-application
STACK: react + typescript + supabase
\`\`\`

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

## 2. Database Schema

### 2.1 Primary Tables

| Table | Description | Relations |
|-------|-------------|-----------|
| users | Core user accounts | has_many: projects |
| projects | User projects | belongs_to: users |
| constraints | Project constraints | belongs_to: projects |

\`\`\`sql
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);
\`\`\`

## 3. API Endpoints

### 3.1 Authentication

- \`POST /api/auth/register\` - User registration
- \`POST /api/auth/login\` - User authentication
- \`POST /api/auth/logout\` - Session termination

### 3.2 Core Resources

\`\`\`
GET    /api/projects          -> List all projects
POST   /api/projects          -> Create new project
GET    /api/projects/:id      -> Get project details
PUT    /api/projects/:id      -> Update project
DELETE /api/projects/:id      -> Remove project
\`\`\`

## 4. Deployment Configuration

\`\`\`yaml
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      
  api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
\`\`\`

## 5. Security Considerations

- [ ] Implement rate limiting on all endpoints
- [ ] Enable RLS policies on database tables
- [ ] Configure CORS for production domains
- [ ] Set up audit logging for sensitive operations

---

> Generated by Concept Generator v1.0
> Timestamp: ${new Date().toISOString()}
`;

const PlanReviewView = ({ planData, onAccept, onHome, onBack }: PlanReviewViewProps) => {
  const [state, setState] = useState<ReviewState>("decision");
  const [feedback, setFeedback] = useState("");
  const [markdownContent] = useState<string>(convertToMarkdown(planData));
  
  const { 
    isListening, 
    status, 
    transcription, 
    audioLevels, 
    toggleListening,
    stopListening 
  } = useVoiceInput({
    simulatedText: "Add GraphQL support and increase rate limits to 1000 req/min...",
    onTranscriptionComplete: (text) => {
      setFeedback(text);
    }
  });

  // Sync transcription to feedback as it types
  useEffect(() => {
    if (transcription && isListening) {
      setFeedback(transcription);
    }
  }, [transcription, isListening]);

  // Stop listening when leaving feedback mode
  useEffect(() => {
    if (state !== "feedback" && isListening) {
      stopListening();
    }
  }, [state, isListening, stopListening]);

  useEffect(() => {
    if (state === "processing") {
      const timer = setTimeout(() => {
        setState("decision");
        setFeedback("");
      }, 3000);
      return () => clearTimeout(timer);
    }
  }, [state]);

  const handleSuggestChanges = () => {
    setState("feedback");
  };

  const handleSubmitFeedback = () => {
    if (feedback.trim()) {
      setState("processing");
    }
  };

  const handleCancelFeedback = () => {
    setState("decision");
    setFeedback("");
  };

  return (
    <div className="min-h-screen flex flex-col animate-fade-in">
      {/* Header */}
      <header className="border-b border-border bg-background sticky top-0 z-10">
        <div className="container max-w-4xl mx-auto px-6 py-4">
          <div className="flex items-center gap-4">
            <HomeButton onClick={onHome} />
            <div className="border-l border-border pl-4">
              <button
                onClick={onBack}
                className="font-mono text-xs text-muted-foreground hover:text-primary transition-all duration-200"
              >
                ← REFINER
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 container max-w-4xl mx-auto px-6 py-8 pb-32">
        {/* Page Header */}
        <div className="text-center mb-8 space-y-3">
          <div className="font-mono text-xs text-primary tracking-widest uppercase">
            [ ARCHITECTURE_REVIEW ]
          </div>
          <h1 className="text-3xl font-bold">Review Technical Plan</h1>
          <p className="text-muted-foreground font-mono text-sm">
            Analyze the generated stack below. Accept or iterate.
          </p>
        </div>

        {state === "processing" ? (
          /* Processing Animation */
          <div className="flex flex-col items-center justify-center py-32 space-y-6">
            <div className="font-mono text-primary text-lg">
              <span className="animate-pulse-slow">[</span>
              <span className="inline-block w-48 overflow-hidden">
                <span className="animate-[slide-loader_1.5s_steps(10)_infinite] inline-block">
                  ||||||||||
                </span>
              </span>
              <span className="animate-pulse-slow">]</span>
            </div>
            <div className="font-mono text-xs text-muted-foreground tracking-widest">
              PROCESSING_UPDATES<span className="animate-blink">_</span>
            </div>
          </div>
        ) : (
          /* Markdown Terminal */
          <div className="space-y-2">
            <div className="font-mono text-xs text-muted-foreground">
              -&gt; GENERATED_SPECIFICATION
            </div>
            <div className="border border-[#333] bg-card p-6 overflow-auto max-h-[60vh]">
              <div className="font-mono text-sm leading-relaxed whitespace-pre-wrap text-muted-foreground">
                {markdownContent.split('\n').map((line, i) => {
                  // Simple markdown-like rendering
                  if (line.startsWith('# ')) {
                    return <h1 key={i} className="text-xl font-bold text-foreground mt-6 mb-3 first:mt-0">{line.slice(2)}</h1>;
                  }
                  if (line.startsWith('## ')) {
                    return <h2 key={i} className="text-lg font-bold text-foreground mt-5 mb-2">{line.slice(3)}</h2>;
                  }
                  if (line.startsWith('### ')) {
                    return <h3 key={i} className="text-base font-semibold text-foreground mt-4 mb-2">{line.slice(4)}</h3>;
                  }
                  if (line.startsWith('#### ')) {
                    return <h4 key={i} className="text-sm font-semibold text-foreground mt-3 mb-1">{line.slice(5)}</h4>;
                  }
                  if (line.startsWith('```')) {
                    return <div key={i} className="text-primary/70">{line}</div>;
                  }
                  if (line.startsWith('- ')) {
                    return <div key={i} className="ml-4 text-muted-foreground">{line}</div>;
                  }
                  if (line.startsWith('|')) {
                    return <div key={i} className="text-muted-foreground/80">{line}</div>;
                  }
                  if (line.startsWith('>')) {
                    return <div key={i} className="border-l-2 border-primary/50 pl-3 text-muted-foreground/70 italic">{line.slice(2)}</div>;
                  }
                  if (line.startsWith('---')) {
                    return <hr key={i} className="border-border my-4" />;
                  }
                  return <div key={i}>{line || '\u00A0'}</div>;
                })}
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Sticky Footer */}
      <footer className="fixed bottom-0 left-0 right-0 border-t border-border bg-[#0A0A0A]">
        <div className="container max-w-4xl mx-auto px-6 py-4">
          {state === "decision" && (
            /* State 1: Decision Mode */
            <div className="flex gap-4">
              <Button
                onClick={onAccept}
                size="lg"
                className="flex-1 py-6 font-bold uppercase tracking-wider bg-[#22c55e] hover:bg-[#16a34a] text-black"
              >
                Accept Plan →
              </Button>
              <Button
                onClick={handleSuggestChanges}
                size="lg"
                className="flex-1 py-6 font-bold uppercase tracking-wider bg-[#ef4444] hover:bg-[#dc2626] text-white"
              >
                Suggest Changes →
              </Button>
            </div>
          )}

          {state === "feedback" && (
            /* State 2: Feedback Input */
            <div className="space-y-3">
              <div className="flex gap-2 items-center">
                <div className="flex-1 bg-muted/50 border border-border">
                  <Input
                    value={feedback}
                    onChange={(e) => setFeedback(e.target.value)}
                    placeholder="Enter modification requirements..."
                    className="bg-transparent border-0 font-mono text-sm placeholder:text-muted-foreground/50 focus-visible:ring-0 focus-visible:ring-offset-0 h-12"
                    disabled={isListening}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && feedback.trim()) {
                        handleSubmitFeedback();
                      }
                      if (e.key === "Escape") {
                        handleCancelFeedback();
                      }
                    }}
                    autoFocus={!isListening}
                  />
                </div>
                <VoiceMicButton
                  isListening={isListening}
                  status={status}
                  audioLevels={audioLevels}
                  onToggle={toggleListening}
                  className="shrink-0"
                />
                <Button
                  onClick={handleSubmitFeedback}
                  disabled={feedback.trim().length === 0}
                  size="lg"
                  className="px-8 font-bold uppercase tracking-wider disabled:opacity-30"
                >
                  Submit →
                </Button>
              </div>
              <div className="flex justify-between">
                <button
                  onClick={handleCancelFeedback}
                  className="font-mono text-xs text-muted-foreground hover:text-primary transition-colors"
                >
                  ← Cancel
                </button>
                <span className="font-mono text-xs text-muted-foreground">
                  Press Enter to submit • Esc to cancel
                </span>
              </div>
            </div>
          )}

          {state === "processing" && (
            /* State 3: Processing indicator in footer */
            <div className="text-center py-2">
              <span className="font-mono text-xs text-primary animate-pulse-slow">
                UPDATING SPECIFICATION...
              </span>
            </div>
          )}
        </div>
      </footer>
    </div>
  );
};

export default PlanReviewView;
